version: '3'

services:
  authentication:
    build: ./services/authentication
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

        
  analytics:
    build: ./services/analytics
    ports:
      - "8001:8001"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001
  
  events:
    build: ./services/events
    ports:
      - "8002:8002"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8002

  
  notifications:
    build: ./services/notifications
    ports:
      - "8003:8003"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8003

  client:
    build: ./client/ui
    ports:
      - "8004:8004"
    depends_on:
      - authentication
      - events
      - notifications
      - analytics
    command: python manage.py runserver 0.0.0.0:8004